In [1]:
import numpy as np

### 创建ndarray

In [2]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data)  # convert data to ndarray
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr[0, 2], arr[0][2]

(3, 3)

In [4]:
arr.ndim  # number of array dimensions

2

In [5]:
arr.shape

(2, 4)

### ndarray的数据类型

In [6]:
arr.dtype

dtype('int64')

In [7]:
np.zeros((2, 3))  # creat a ndarray with all elements are 0

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.empty((2, 3))  # creat a ndarray with random elements

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [9]:
np.arange(1, 13, 2)  # creat a ndarray with start, end, step

array([ 1,  3,  5,  7,  9, 11])

In [10]:
np.ones((2, 3))  # creat a ndarray with all elements are 1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [11]:
np.ones((2, 3)).astype(np.int64)  # creat a new ndarray by change all it elements' type

array([[1, 1, 1],
       [1, 1, 1]])

### 数组和标量之间的运算

In [12]:
arr, arr + arr

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 2,  4,  6,  8],
        [10, 12, 14, 16]]))

### 布尔型索引

In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Bob'])
data = np.random.randn(5, 3)
names, data

(array(['Bob', 'Joe', 'Will', 'Joe', 'Bob'],
       dtype='<U4'), array([[ 0.6116061 ,  0.39284986,  1.49525458],
        [-1.83973614, -1.46836273,  0.38902788],
        [-0.30271474, -0.01110926,  1.02898152],
        [-0.74856721,  1.4305681 ,  0.5095104 ],
        [ 0.51930758, -0.09817539, -0.57595081]]))

In [14]:
names == 'Bob'

array([ True, False, False, False,  True], dtype=bool)

In [15]:
data[names == 'Bob']

array([[ 0.6116061 ,  0.39284986,  1.49525458],
       [ 0.51930758, -0.09817539, -0.57595081]])

In [16]:
data[names == 'Bob', :2]

array([[ 0.6116061 ,  0.39284986],
       [ 0.51930758, -0.09817539]])

In [18]:
data[names == 'Bob', 1]

array([ 0.39284986, -0.09817539])

In [19]:
names != 'Bob'  # this is equivalent to "-(names == 'Bob')"

array([False,  True,  True,  True, False], dtype=bool)

In [22]:
# the keywords "and" and "or" is invalid in Boolean ndarray, use "&" and "|" instead
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True, False,  True], dtype=bool)

In [23]:
data[data < 0] = 0  # elements assignment
data

array([[ 0.6116061 ,  0.39284986,  1.49525458],
       [ 0.        ,  0.        ,  0.38902788],
       [ 0.        ,  0.        ,  1.02898152],
       [ 0.        ,  1.4305681 ,  0.5095104 ],
       [ 0.51930758,  0.        ,  0.        ]])

### 花式索引

In [24]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
    
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [27]:
arr[[4, 3, 0, 6]], arr[[-1, -3]]

(array([[ 4.,  4.,  4.,  4.],
        [ 3.,  3.,  3.,  3.],
        [ 0.,  0.,  0.,  0.],
        [ 6.,  6.,  6.,  6.]]), array([[ 7.,  7.,  7.,  7.],
        [ 5.,  5.,  5.,  5.]]))

In [28]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [34]:
arr[[0, 5, 7], [0, 1, 2]]

array([ 0, 21, 30])

In [36]:
arr[[0, 5, 7]][:, [0, 1, 2]]  # this is equivalent to arr[np.ix_([0, 5, 7], [0, 1, 2])]

array([[ 0,  1,  2],
       [20, 21, 22],
       [28, 29, 30]])

### 数组转置

In [37]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
arr.T  # this will not modify the original array

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### GramSchmidtProcess

In [13]:
# GRADED FUNCTION
import numpy as np
import numpy.linalg as la

verySmallNumber = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001

mA = np.arange(16).reshape((4, 4))
la.norm(mA[:, 0])

14.966629547095765

In [11]:

# Our first function will perform the Gram-Schmidt procedure for 4 basis vectors.
# We'll take this list of vectors as the columns of a matrix, A.
# We'll then go through the vectors one at a time and set them to be orthogonal
# to all the vectors that came before it. Before normalising.
# Follow the instructions inside the function at each comment.
# You will be told where to add code to complete the function.
def gsBasis4(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # The zeroth column is easy, since it has no other vectors to make it normal to.
    # All that needs to be done is to normalise it. I.e. divide by its modulus, or norm.
    B[:, 0] = B[:, 0] / la.norm(B[:, 0])
    # For the first column, we need to subtract any overlap with our new zeroth vector.
    B[:, 1] = B[:, 1] - B[:, 1] @ B[:, 0] * B[:, 0]
    # If there's anything left after that subtraction, then B[:, 1] is linearly independant of B[:, 0]
    # If this is the case, we can normalise it. Otherwise we'll set that vector to zero.
    if la.norm(B[:, 1]) > verySmallNumber :
        B[:, 1] = B[:, 1] / la.norm(B[:, 1])
    else :
        B[:, 1] = np.zeros_like(B[:, 1])
    # Now we need to repeat the process for column 2.
    # Insert two lines of code, the first to subtract the overlap with the zeroth vector,
    # and the second to subtract the overlap with the first.
    
    
    # Again we'll need to normalise our new vector.
    # Copy and adapt the normalisation fragment from above to column 2.
    
    
    
    
    # Finally, column three:
    # Insert code to subtract the overlap with the first three vectors.
    
    
    
    # Now normalise if possible
    
    
    
    
    # Finally, we return the result:
    return B
gsBasis4(mA)

array([[ 0.        ,  0.83666003,  2.        ,  3.        ],
       [ 0.26726124,  0.47809144,  6.        ,  7.        ],
       [ 0.53452248,  0.11952286, 10.        , 11.        ],
       [ 0.80178373, -0.23904572, 14.        , 15.        ]])

In [ ]:
# The second part of this exercise will generalise the procedure.
# Previously, we could only have four vectors, and there was a lot of repeating in the code.
# We'll use a for-loop here to iterate the process for each vector.
def gsBasis(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]) :
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i) :
            # Complete the code to subtract the overlap with previous vectors.
            # you'll need the current vector B[:, i] and a previous vector B[:, j]
            B[:, i] = 
        # Next insert code to do the normalisation test for B[:, i]
        if :
            
        
            
    # Finally, we return the result:
    return B

In [ ]:
# This function uses the Gram-schmidt process to calculate the dimension
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero,
# the sum of all the norms will be the dimension.
def dimensions(A) :
    return np.sum(la.norm(gsBasis(A), axis=0))