In [1]:
import numpy as np

In [23]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data)  # convert data to ndarray
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr[0, 2], arr[0][2]

(3, 3)

In [3]:
arr.ndim  # number of array dimensions

2

In [5]:
arr.shape

(2, 4)

In [6]:
arr.dtype

dtype('int64')

In [8]:
np.zeros((2, 3))  # creat a ndarray with all elements are 0

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
np.empty((2, 3))  # creat a ndarray with random elements

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.arange(1, 13, 2)  # creat a ndarray with start, end, step

array([ 1,  3,  5,  7,  9, 11])

In [16]:
np.ones((2, 3))  # creat a ndarray with all elements are 1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
np.ones((2, 3)).astype(np.int64)  # creat a new ndarray by change all it elements' type

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
arr, arr + arr

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 2,  4,  6,  8],
        [10, 12, 14, 16]]))

In [28]:
names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Bob'])
data = np.random.randn(5, 3)
names, data

(array(['Bob', 'Joe', 'Will', 'Joe', 'Bob'], 
       dtype='<U4'), array([[ 1.05602981, -1.58983866,  0.60973894],
        [-0.10501829,  2.36745513, -1.19659952],
        [-0.66412727, -0.40566971, -1.07464165],
        [ 0.6362316 , -0.98627455, -0.53851089],
        [ 1.14709231, -0.90102402, -1.39152923]]))

In [29]:
names == 'Bob'

array([ True, False, False, False,  True], dtype=bool)

In [31]:
data[names == 'Bob']

array([[ 1.05602981, -1.58983866,  0.60973894],
       [ 1.14709231, -0.90102402, -1.39152923]])

In [32]:
data[names == 'Bob', :2]

array([[ 1.05602981, -1.58983866],
       [ 1.14709231, -0.90102402]])